all:
	gcc -Wall -O2 -I${PREFIX}/include/X11 -L${PREFIX}/X11R6/lib Partridge.c -o Partridge -lm -lXt -lX11 -lXpm
#	gcc -Wall -g -I${PREFIX}/include/X11 -L${PREFIX}/X11R6/lib Partridge.c -o Partridge -lm -lXt -lX11 -lXpm

