all:
	gcc -Wall -O2 -I/usr/include/X11 -I${PREFIX}/include/X11 -L/usr/X11R6/lib -L${PREFIX}/X11R6/lib Partridge.c -o Partridge -lm -lXt -lX11 -lXpm
#	gcc -Wall -g2 -I/usr/include/X11 -I${PREFIX}/include/X11 -L/usr/X11R6/lib -L${PREFIX}/X11R6/lib Partridge.c -o Partridge -lm -lXt -lX11 -lXpm

