all:
	gcc -g nautyex_coxeter.c nautyL1.a -o nautyex_coxeter
	gcc -g nautyex_fano.c nautyL1.a -o nautyex_fano
	gcc -g nautyex_STS_2-5-21.c nautyL1.a -o nautyex_STS_2-5-21
	gcc -g nautyex_pappus.c nautyL1.a -o nautyex_pappus
	gcc -g nautyex_desargues.c nautyL1.a -o nautyex_desargues

clean:
	rm -f nautyex_coxeter nautyex_fano nautyex_STS_2-5-21 nautyex_pappus nautyex_desargues
